### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by paulmartinetti** [Bellafaire/Android-Companion-App-For-BLE-Devices#1]
Thanks for this project. My device, a Note 8, runs a new project in Android Studio, but I get this error when I import this project. It won't allow me to select my device or any device to run the project.

4:32 PM	Gradle sync failed: com.android.tools.idea.gradle.project.sync.idea.issues.SdkPlatformNotFoundException: Module: 'app' platform 'android-29' not found. (22 s 383 ms)

**Comment by Bellafaire** [comment]
I believe that error indicates that you do not have the API 29 platform installed to your version of android studios. If you are using this project I highly reccomend taking a look at the newest update to the project which is an overall improvement in functionality.
