### ISSUE TITLE
Is there any way to maximize energy efficiency through software?

### ISSUE THREAD

**Issue by themelispan** [Bellafaire/Android-Companion-App-For-BLE-Devices#7]
Your current example code uses void loop() and pings the phone every one second which I suppose is for the sake of keeping it simple.

Is there any way that I could get a special message on my esp whenever the phone receives a new notification (and then do a request from the esp using the /notification command) so that I don't have to ping it all the time? This looks incredibly wasteful of energy

**Comment by Bellafaire** [comment]
At the moment no such feature exists in this app, it's in need of some reworking. Personally in my watch project for which this app was designed (https://github.com/Bellafaire/ESP32-Smart-Watch) I poll the phone only once when the watch wakes from sleep. After the first connection the app spawns a background service and will automatically reconnect to the ESP32 as long as its advertising. There's currently no way to check the number of notifications other than to read the full string, I'm thinking of ways to improve this app but I'm not totally sure on which direction to take it quite yet.

**Comment by themelispan** [comment]
The number of notification can be counted using the /notifications command but that's not my problem. I want to be notified on my ESP32 in real time so currently, pinging the phone all the time is my only option

**Comment by Bellafaire** [comment]
This feature is now supported, the ESP32 example shows how to receive a callback on notifications being posted or removed.
